Migrated to Sound Null Safety
fireslime/photo_view pull request #375
Opened 2020-11-21 14:21 UTC by DevNico

As mentioned in #374 this is my PR for the migration to Sound Null Safety. All tests pass but the example will not run in sound null safety mode until [flutter_svg](https://github.com/dnfield/flutter_svg) is migrated. I opened an issue about migration [there](https://github.com/dnfield/flutter_svg/issues/453) as well.

2020-11-23 10:07 UTC, renancaraujo commented on .vscode/settings.json
> +	"dart.lineLength": 80
How abot adding .`vscode` to `.gitignore`?

2020-11-23 10:09 UTC, DevNico commented on .vscode/settings.json
> +	"dart.lineLength": 80
I did think about that but I thought since 80 line length seems to be the coding style of your project it wouldn't hurt to have that setting in there. If you want it removed I'll remove it of course.

2020-11-23 12:34 UTC, DevNico commented on .vscode/settings.json
> +	"dart.lineLength": 80
@renancaraujo What do you think?

2020-11-24 10:08 UTC, renancaraujo commented on .vscode/settings.json
> +	"dart.lineLength": 80
No need for now. I'm gonna give it a look ASAP. Thanks.

2021-01-28 12:38 UTC, nohli commented
@DevNico
FYI The mentioned issue is closed and there is a nullsafe flutter_svg prerelease: https://pub.dev/packages/flutter_svg/versions/0.20.0-nullsafety.3

2021-01-28 12:40 UTC, DevNico commented
Alright haven't had much time recently due to work / exams. Will look at this again end of next week.

2021-02-01 07:58 UTC, DevNico commented
Should be ready for review now.

2021-03-02 22:54 UTC, nilsreichardt commented
@DevNico You can add 'Closes #374' to your PR description. This will automatically close the issue when this PR is merged :)

2021-03-02 22:56 UTC, nilsreichardt commented on .vscode/settings.json
> +	"dart.lineLength": 80
In the perfect world this would be a separate PR ;)

2021-03-04 22:42 UTC, dvaldivia commented
This PR is even more relevant with Flutter 2, anything I can help you test?

2021-03-05 09:57 UTC, SergeShkurko requested changes
Maybe make `_imageChunkEvent ` nullable?

2021-03-05 09:57 UTC, SergeShkurko commented on lib/src/photo_view_wrappers.dart
> +      return widget.loadingBuilder!(context, _imageChunkEvent!);
i got a non critical problem when use `PhotoViewGallery.builder` (console spam, but works normally)

![image](https://user-images.githubusercontent.com/18213789/110098875-ba1bce80-7db1-11eb-8353-bf2a22902b5d.png)

2021-03-06 02:57 UTC, fzyzcjy commented
This is very helpful PR! Is there anything I can help?

2021-03-06 10:09 UTC, DevNico commented on lib/src/photo_view_wrappers.dart
> +      return widget.loadingBuilder!(context, _imageChunkEvent!);
I removed it must have overlooked that.

2021-03-07 13:24 UTC, renancaraujo commented
Thank you so much for this contribution and sorry for the dalay!

2021-03-07 13:24 UTC, renancaraujo approved these changes

2021-03-07 13:24 UTC, merged